export const itemListBodies =  [
    {
      linkTo: "mens-clothing",
      category: `men's clothing`,
      name1: "Najnowsze",
      arg1: "new",
      name2: "Bestsellery",
      arg2: "bestsellers",
      name3: "Wyprzedaż",
      arg3: "sale",
    },
    {
      linkTo: "jewelery",
      category: "jewelery",
      name1: "Najnowsze",
      arg1: "new",
      name2: "Bestsellery",
      arg2: "bestsellers",
      name3: "Wyprzedaż",
      arg3: "sale",
    },
    {
      linkTo: "electronics",
      category: "electronics",
      name1: "Najnowsze",
      arg1: "new",
      name2: "Bestsellery",
      arg2: "bestsellers",
      name3: "Wyprzedaż",
      arg3: "sale",
    },
    {
      linkTo: "womens-clothing",
      category: `women's clothing`,
      name1: "Najnowsze",
      arg1: "new",
      name2: "Bestsellery",
      arg2: "bestsellers",
      name3: "Wyprzedaż",
      arg3: "sale",
    },
  ];